import type { NormalizedAircraft } from '@/types/aircraft';
import { DEFAULT_LAT, DEFAULT_LON } from './constants';
import { distanceMi } from './geo';

/** Deterministic mock fleet for offline UI development */
export function getMockAircraft(
  centerLat = DEFAULT_LAT,
  centerLon = DEFAULT_LON
): NormalizedAircraft[] {
  const seeds: Omit<NormalizedAircraft, 'distanceMi'>[] = [
    {
      hex: 'a1b2c3',
      callsign: 'UAL1234',
      lat: centerLat + 0.04,
      lon: centerLon - 0.03,
      altitudeFt: 8200,
      groundSpeedKt: 245,
      headingDeg: 110,
      verticalRateFpm: -1200,
      category: 'A3',
      aircraftType: 'B738',
      squawk: '4521',
      seenSecondsAgo: 2,
    },
    {
      hex: 'd4e5f6',
      callsign: 'SWA2847',
      lat: centerLat - 0.02,
      lon: centerLon + 0.05,
      altitudeFt: 14500,
      groundSpeedKt: 310,
      headingDeg: 285,
      verticalRateFpm: 800,
      category: 'A3',
      aircraftType: 'B737',
      squawk: '1200',
      seenSecondsAgo: 1,
    },
    {
      hex: 'g7h8i9',
      callsign: 'FFT901',
      lat: centerLat + 0.01,
      lon: centerLon - 0.01,
      altitudeFt: 4200,
      groundSpeedKt: 165,
      headingDeg: 45,
      verticalRateFpm: -600,
      category: 'A3',
      aircraftType: 'A20N',
      seenSecondsAgo: 3,
    },
    {
      hex: 'j0k1l2',
      callsign: 'DAL1888',
      lat: centerLat - 0.05,
      lon: centerLon - 0.04,
      altitudeFt: 32000,
      groundSpeedKt: 420,
      headingDeg: 200,
      verticalRateFpm: 0,
      category: 'A3',
      aircraftType: 'A321',
      seenSecondsAgo: 4,
    },
    {
      hex: 'm3n4o5',
      callsign: 'RPA4520',
      lat: centerLat + 0.03,
      lon: centerLon + 0.02,
      altitudeFt: 11800,
      groundSpeedKt: 198,
      headingDeg: 330,
      verticalRateFpm: 450,
      category: 'A3',
      aircraftType: 'E75L',
      squawk: '4523',
      seenSecondsAgo: 8,
    },
    {
      hex: 'p6q7r8',
      callsign: 'AAL456',
      lat: centerLat - 0.01,
      lon: centerLon + 0.03,
      altitudeFt: 6500,
      groundSpeedKt: 220,
      headingDeg: 95,
      verticalRateFpm: -900,
      category: 'A3',
      aircraftType: 'B38M',
      squawk: '7700',
      seenSecondsAgo: 2,
    },
    {
      hex: 's9t0u1',
      callsign: 'SKW5340',
      lat: centerLat + 0.06,
      lon: centerLon - 0.06,
      altitudeFt: 28000,
      groundSpeedKt: 390,
      headingDeg: 15,
      verticalRateFpm: 50,
      category: 'A3',
      aircraftType: 'E75L',
      seenSecondsAgo: 5,
    },
    {
      hex: 'v2w3x4',
      callsign: 'JBU512',
      lat: centerLat - 0.03,
      lon: centerLon - 0.02,
      altitudeFt: 9800,
      groundSpeedKt: 275,
      headingDeg: 160,
      verticalRateFpm: 1100,
      category: 'A3',
      aircraftType: 'A320',
      seenSecondsAgo: 1,
    },
    {
      hex: 'y5z6a7',
      callsign: 'ASA789',
      lat: centerLat + 0.02,
      lon: centerLon + 0.06,
      altitudeFt: 21000,
      groundSpeedKt: 350,
      headingDeg: 250,
      verticalRateFpm: 0,
      category: 'A3',
      aircraftType: 'B739',
      seenSecondsAgo: 6,
    },
    {
      hex: 'b8c9d0',
      callsign: 'ENY2105',
      lat: centerLat - 0.04,
      lon: centerLon + 0.01,
      altitudeFt: 7500,
      groundSpeedKt: 140,
      headingDeg: 70,
      verticalRateFpm: -200,
      category: 'A3',
      aircraftType: 'E170',
      squawk: '1200',
      seenSecondsAgo: 12,
    },
    {
      hex: 'c1d2e3',
      callsign: 'N172SP',
      registration: 'N172SP',
      lat: centerLat + 0.035,
      lon: centerLon - 0.02,
      altitudeFt: 6500,
      groundSpeedKt: 105,
      headingDeg: 180,
      verticalRateFpm: 300,
      category: 'A1',
      aircraftType: 'C172',
      seenSecondsAgo: 9,
    },
    {
      hex: 'd4e5f7',
      callsign: 'N550GP',
      registration: 'N550GP',
      lat: centerLat - 0.055,
      lon: centerLon - 0.03,
      altitudeFt: 43000,
      groundSpeedKt: 448,
      headingDeg: 265,
      verticalRateFpm: 0,
      category: 'A3',
      aircraftType: 'GLF5',
      seenSecondsAgo: 4,
    },
    {
      hex: 'e8f9a0',
      callsign: 'RCH1234',
      lat: centerLat + 0.08,
      lon: centerLon + 0.03,
      altitudeFt: 26000,
      groundSpeedKt: 405,
      headingDeg: 90,
      verticalRateFpm: 0,
      category: 'A5',
      aircraftType: 'C17',
      squawk: '7777',
      seenSecondsAgo: 3,
    },
    {
      hex: 'f1a2b3',
      callsign: 'N628TS',
      registration: 'N628TS',
      lat: centerLat - 0.07,
      lon: centerLon + 0.05,
      altitudeFt: 44000,
      groundSpeedKt: 462,
      headingDeg: 240,
      verticalRateFpm: 150,
      category: 'A3',
      aircraftType: 'GLF6',
      seenSecondsAgo: 2,
    },
  ];

  return seeds.map((ac) => ({
    ...ac,
    distanceMi: distanceMi(centerLat, centerLon, ac.lat, ac.lon),
  }));
}
